{
 "title": "Example Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "example_go_metrics_orders_request_processing_time_summary_ms{quantile=\"0.99\"}",
     "legendFormat": "p99"
    },
    {
     "expr": "example_go_metrics_orders_request_processing_time_summary_ms{quantile=\"0.9\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "example_go_metrics_orders_request_processing_time_summary_ms{quantile=\"0.5\"}",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Histogram Latency Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(example_go_metrics_orders_request_processing_time_histogram_ms_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(example_go_metrics_orders_request_processing_time_histogram_ms_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(example_go_metrics_orders_request_processing_time_histogram_ms_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Выполняемые запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "example_go_metrics_orders_work_order_create{instance=\"order:8082\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Статусы запросов",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "example_go_metrics_orders_request_send{instance=\"order:8082\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}